# Generated by Django 6.1.1 on 2026-09-19 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('text', 'Text (prose with optional image)'), ('facts', 'Quick Facts (label/value cards)'), ('list', 'List / checklist'), ('steps', 'Numbered steps'), ('table', 'Table'), ('banner', 'Photo banner')], default='text', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('items', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='country-sections/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.country')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
