# Generated by Django 6.1.1 on 2026-09-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_intake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intake',
            options={'ordering': ['start_date', 'created_at']},
        ),
        migrations.AddField(
            model_name='intake',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
