# Generated by Django 6.1.1 on 2026-09-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_intake_options_intake_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='country',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='countrysection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testpreparation',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='university',
            name='image_url',
        ),
    ]
