# Generated by Django 6.1.1 on 2026-10-04 05:21

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def categories_become_sections(apps, schema_editor):
    """Turn the old free-text gallery `category` values into GallerySection rows."""
    GalleryImage = apps.get_model("api", "GalleryImage")
    GallerySection = apps.get_model("api", "GallerySection")

    categories = (
        GalleryImage.objects.order_by()
        .values_list("category", flat=True)
        .distinct()
    )
    for order, category in enumerate(categories):
        name = (category or "").strip()
        if not name:
            continue
        slug = slugify(name) or "gallery-section"
        suffix = 1
        while GallerySection.objects.filter(slug=slug).exists():
            suffix += 1
            slug = f"{slugify(name) or 'gallery-section'}-{suffix}"
        section = GallerySection.objects.create(name=name, slug=slug, order=order)
        GalleryImage.objects.filter(category=category).update(section=section)


def sections_become_categories(apps, schema_editor):
    GalleryImage = apps.get_model("api", "GalleryImage")
    GalleryImage.objects.update(category="")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.gallerysection'),
        ),
        migrations.RunPython(categories_become_sections, sections_become_categories),
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
    ]
