"""
Django settings for bristi_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import dotenv
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


dotenv.load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-139#!v%%86ohmw7s_^hfc=*mzs!6ily3gx#ly2j%z!7$!h&i1j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# nginx terminates TLS and proxies to Django over plain http, so without this
# every absolute URL DRF builds (media images, pagination links) comes back as
# http:// instead of https://. Only trusted when the proxy sets the header.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Allow overriding via env vars (comma separated)
import os
_env_cors = os.getenv("CORS_ALLOWED_ORIGINS")
if _env_cors:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _env_cors.split(",") if o.strip()]

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True").lower() == "true"

ROOT_URLCONF = 'bristi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bristi_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

PRODUCTION = os.environ.get('PRODUCTION', 'False') == 'True'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if not PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB'),
            'USER': os.environ.get('POSTGRES_USER'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
            'HOST': os.environ.get('POSTGRES_HOST'),
            'PORT': os.environ.get('POSTGRES_PORT'),
            'CONN_MAX_AGE': 600,  # Allow persistent connections
            'OPTIONS': {
                'connect_timeout': 10,  # Timeout for initial connection
            },
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------------------------
# Cloudflare R2 (S3-compatible) storage — ON by default (S3 is the default
# storage backend).
#
# USE_R2=False         -> media stays on local disk
# USE_R2_STATIC=False  -> `collectstatic` writes to local disk instead of R2
#
# Credentials come from R2_* vars, with the native django-storages AWS_* names
# accepted as aliases. All-empty -> local-disk fallback (dev before keys);
# a *partial* configuration is a hard error so typos never go live unnoticed.
# All generated media/static URLs are built from R2_PUBLIC_URL, kept in sync
# with the frontend's NEXT_PUBLIC_R2_PUBLIC_URL.
# ---------------------------------------------------------------------------

def _env_flag(name, default="True"):
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


def _env(*names):
    """First non-empty value among the given env var names."""
    for name in names:
        value = os.getenv(name, "").strip()
        if value:
            return value
    return ""


USE_R2 = _env_flag("USE_R2")
USE_R2_STATIC = _env_flag("USE_R2_STATIC")

R2_ACCOUNT_ID = _env("R2_ACCOUNT_ID")
R2_ENDPOINT_URL = _env("R2_ENDPOINT_URL", "AWS_S3_ENDPOINT_URL") or (
    f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com" if R2_ACCOUNT_ID else ""
)
R2_BUCKET_NAME = _env("R2_BUCKET_NAME", "AWS_STORAGE_BUCKET_NAME")
R2_ACCESS_KEY_ID = _env("R2_ACCESS_KEY_ID", "AWS_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = _env("R2_SECRET_ACCESS_KEY", "AWS_SECRET_ACCESS_KEY")
R2_PUBLIC_URL = _env("R2_PUBLIC_URL", "AWS_S3_CUSTOM_DOMAIN").rstrip("/")
R2_REGION = _env("R2_REGION") or "auto"

_R2_REQUIRED = (
    ("R2_ACCOUNT_ID (or R2_ENDPOINT_URL)", R2_ENDPOINT_URL),
    ("R2_BUCKET_NAME", R2_BUCKET_NAME),
    ("R2_ACCESS_KEY_ID", R2_ACCESS_KEY_ID),
    ("R2_SECRET_ACCESS_KEY", R2_SECRET_ACCESS_KEY),
    ("R2_PUBLIC_URL", R2_PUBLIC_URL),
)
_R2_MISSING = [name for name, value in _R2_REQUIRED if not value]

if (USE_R2 or USE_R2_STATIC) and _R2_MISSING:
    if len(_R2_MISSING) == len(_R2_REQUIRED):
        # Nothing configured yet: run on local disk (dev / pre-credentials).
        import warnings

        USE_R2 = USE_R2_STATIC = False
        warnings.warn(
            "Cloudflare R2 credentials are not set; falling back to local "
            "filesystem storage. Set the R2_* variables in backend/.env to "
            "enable R2.",
            RuntimeWarning,
        )
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "Cloudflare R2 storage is partially configured. Missing: "
            + ", ".join(_R2_MISSING)
        )

if USE_R2 or USE_R2_STATIC:
    # Accept either a full URL or a bare hostname.
    AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_URL.split("://")[-1].split("/")[0]

    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = R2_ENDPOINT_URL
    AWS_S3_REGION_NAME = R2_REGION
    AWS_S3_ADDRESSING_STYLE = "path"  # R2 does not resolve bucket subdomains
    AWS_QUERYSTRING_AUTH = False  # public bucket, stable/cacheable URLs
    AWS_DEFAULT_ACL = None  # R2 objects ignore ACLs; access is bucket policy
    AWS_S3_FILE_OVERWRITE = True  # keep upload_to paths stable across re-uploads
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "public, max-age=3600"}

    STORAGES = {
        "default": {
            "BACKEND": (
                "storages.backends.s3.S3Storage"
                if USE_R2
                else "django.core.files.storage.FileSystemStorage"
            ),
        },
        "staticfiles": {
            "BACKEND": (
                "storages.backends.s3.S3StaticStorage"
                if USE_R2_STATIC
                else "django.contrib.staticfiles.storage.StaticFilesStorage"
            ),
        },
    }

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 30,
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
